name: "Bambulab Timelapse"
description: "Télécharge et convertit automatiquement les timelapses de votre imprimante Bambu Lab P1S"
version: "0.2.0"
slug: "bambulab_timelapse"
url: "https://github.com/gubas/homeassistant-addons"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
homeassistant_api: true
ingress: true
ingress_port: 8099
panel_icon: mdi:video-vintage
panel_title: "Timelapses Bambulab"
panel_admin: false
host_network: true
ports:
  5000/tcp: 5000
startup: application
boot: auto
map:
  - share:rw
options:
  bambu_email: ""
  bambu_password: ""
  bambu_region: "China"
  printer_serial: ""
  auto_download: true
  convert_to_mp4: true
  resolution: "original"
  notify_on_complete: true
schema:
  bambu_email: str
  bambu_password: password
  bambu_region: list(China|Europe|USA)
  printer_serial: str
  auto_download: bool
  convert_to_mp4: bool
  resolution: list(original|1080p|720p|480p)
  notify_on_complete: bool
