name: "Bambulab Timelapse"
description: "Télécharge et convertit automatiquement les timelapses de votre imprimante Bambu Lab P1S"
version: "0.1.1"
slug: "bambulab_timelapse"
url: "https://github.com/gubas/homeassistant-addons"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
homeassistant_api: true
ingress: true
ingress_port: 8099
panel_icon: mdi:video-vintage
panel_title: "Timelapses Bambulab"
panel_admin: false
startup: application
boot: auto
map:
  - share:rw
options:
  printer_ip: ""
  printer_access_code: ""
  printer_serial: ""
  auto_download: true
  convert_to_mp4: true
  resolution: "original"
  notify_on_complete: true
schema:
  printer_ip: str
  printer_access_code: str
  printer_serial: str
  auto_download: bool
  convert_to_mp4: bool
  resolution: list(original|1080p|720p|480p)
  notify_on_complete: bool
