display:
  name: Display Icon
  description: Affiche une icône sur WLED
  fields:
    icon_id:
      name: Icon ID
      description: ID de l'icône
      selector:
        text:

stop:
  name: Stop
  description: Arrête l'animation
  fields:
    host:
      name: Host
      description: IP WLED
      selector:
        text:
