name: "Filament Manager"
description: "Gestionnaire de filaments 3D avec suivi de consommation et statistiques"
version: "0.2.5"
slug: "filament_manager"
url: "https://github.com/gubas/homeassistant-addons"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
ingress: true
ingress_port: 5001
panel_icon: mdi:printer-3d-nozzle
panel_title: "Filament Manager"
panel_admin: false
ports:
  5001/tcp: 5001
ports_description:
  5001/tcp: "Interface web du gestionnaire de filaments"
webui: "http://[HOST]:[PORT:5001]"
startup: application
boot: auto
options:
  printer_entity: "sensor.p1s_print_progress"
  currency: "EUR"
  weight_unit: "g"
  low_stock_threshold: 200
schema:
  printer_entity: str
  currency: str
  weight_unit: str
  low_stock_threshold: int
